# Generated by Django 3.2.9 on 2021-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_auto_20211104_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='imageLink',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
