# Generated by Django 3.2.9 on 2021-11-06 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main1', '0003_goodstype_imagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='gCount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='cLinkAddr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='goodstype',
            old_name='tLinkAddr',
            new_name='addr',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='gSum',
        ),
        migrations.AlterField(
            model_name='cart',
            name='linkG',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main1.good'),
        ),
        migrations.CreateModel(
            name='gComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(max_length=300)),
                ('linkG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main1.good')),
                ('linkU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
